// Auto-generated by Netlify build step
window.INFINITY_GEMINI_API_KEY = "";
window.GEMINI_API_KEY = "";
window.INFINITY_GEMINI_MODEL = "gemini-3.1-flash-lite-image";
window.GEMINI_MODEL = "gemini-3.1-flash-lite-image";
